config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get  '/pages',    to: 'static_pages#pages', as: 'pages'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'  
  delete '/login', to: 'sessions#destroy'
  resources :users
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    The
    %a{:href => "http://www.railstutorial.org/"} Ruby on Rails Tutorial
    by
    %a{:href => "http://www.michaelhartl.com/"} Michael Hartl
  %nav
    %ul
      %li= link_to "About",   about_path
      %li
        %a{:href => "http://news.railstutorial.org/"} News

app/views/layouts/_header.html.haml
%body
  %header.navbar.navbar-fixed-top.navbar-inverse
    .container
      = link_to "sample app", root_path, id: "logo"
      %nav
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Home", root_path
          %li= link_to "pages", pages_path
          - if logged_in?
            %li= link_to "Users", users_path
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Account
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Profile", current_user
                %li= link_to "Settings", edit_user_path(current_user)
                %li.divider
                %li
                  = link_to "Log out", logout_path, method: :delete
          - else
            %li= link_to "Log in", login_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= fulltitle(yield(:title))
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', |
      'data-turbolinks-track': 'reload'                   |
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        %div{:class => "alert alert-#{message_type}"}= message
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?